# Site settings
title: The mismeasure of things
email: les_pas_perdus@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: "/college/"
url:  "http://gianniecce.github.io"
twitter_username: giacomoecce
github_username:  giacomovagni

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


